version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-lib:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run build:cjs
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run test-coverage
      - run: npm run codecov
  lint-lib:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/project/.npmrc
      - run: npm publish . --access public

workflows:
  version: 2
  test-deploy:
    jobs:
      - build-lib:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build-lib
          filters:
            tags:
              ignore: /.*/
      - lint-lib:
          requires:
            - build-lib
          filters:
            tags:
              ignore: /.*/
      - publish:
          requires:
            - build-lib
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
